User added

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -71,6 +71,7 @@ jobs:
         run: |
           echo "EC2_IP=$(terraform output -raw ec2_instance_public_ip)" \
           >> $GITHUB_ENV
+          echo "Connecting to EC2 IP: $EC2_IP"
 
       - name: Restore SSH key
         run: |
@@ -82,15 +83,34 @@ jobs:
           terraform output -raw tls_cert > cert.pem
           terraform output -raw tls_key > tls.key
 
+      - name: Installing nginx if needed
+        run: |
+          echo "Installing and configuring NGINX on EC2..."
+
+          ssh  -o StrictHostKeyChecking=no -i key.pem \
+          $TF_VAR_dev_username@$EC2_IP <<'EOF'
+            # Check if nginx is installed
+            if ! command -v nginx > /dev/null; then
+              echo "NGINX not found. Installing..."
+              sudo apt update
+              sudo apt install -y nginx
+              sudo systemctl enable nginx
+              sudo systemctl start nginx
+            else
+              echo "NGINX is already installed."
+            fi
+          EOF
+
       - name: Upload TLS to EC2 & Configure NGINX
         run: |
           echo "Uploading certs and configuring NGINX on EC2..."
           scp -o StrictHostKeyChecking=no \
               -i key.pem \
               cert.pem tls.key \
-              ubuntu:$EC2_IP:/tmp/
+              $TF_VAR_dev_username:$EC2_IP:/tmp/
 
-          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP <<EOF
+          ssh -o StrictHostKeyChecking=no -i key.pem \
+          $TF_VAR_dev_username@$EC2_IP <<EOF
             sudo mkdir -p /etc/nginx/ssl
             sudo mv /tmp/cert.pem /etc/nginx/ssl/
             sudo mv /tmp/tls.key /etc/nginx/ssl/
@@ -140,7 +160,8 @@ jobs:
         run: |
           echo "Creating Kubernetes TLS Secret in K3s cluster..."
 
-          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP <<'EOF'
+          ssh -o StrictHostKeyChecking=no -i key.pem \
+          $TF_VAR_dev_username@$EC2_IP <<'EOF'
             kubectl get secret tls-secret >/dev/null 2>&1 || \
             kubectl create secret tls tls-secret \
               --cert=/etc/nginx/ssl/cert.pem \
@@ -158,12 +179,13 @@ jobs:
 
           # Deployment-Dateien nach EC2 kopieren
           scp -o StrictHostKeyChecking=no -i key.pem -r ./k8s/wordpress \
-            ubuntu@$EC2_IP:/home/ubuntu/
+            $TF_VAR_dev_username@$EC2_IP:/home/ubuntu/
           scp -o StrictHostKeyChecking=no -i key.pem -r ./k8s/prestashop \
-            ubuntu@$EC2_IP:/home/ubuntu/
+            $TF_VAR_dev_username@$EC2_IP:/home/ubuntu/
 
           # Remote SSH + K8s Apply
-          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP <<'EOF'
+          ssh -o StrictHostKeyChecking=no -i key.pem \
+          ubuntu@$EC2_IP <<'EOF'
             echo "Setzen der Umgebungsvariablen..."
             export DB_ENDPOINT=${{ env.DB_ENDPOINT }}
             export DB_NAME=${{ env.DB_NAME }}
@@ -191,16 +213,17 @@ jobs:
         run: |
           echo "Uploading install-monitoring.sh to EC2 and executing it..."
           scp -o StrictHostKeyChecking=no -i key.pem install-monitoring.sh \
-            ubuntu@$EC2_IP:/home/ubuntu/
-
-           ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP <<'EOF'
-             chmod +x /home/ubuntu/install-monitoring.sh
-             bash /home/ubuntu/install-monitoring.sh
-           EOF
+          $TF_VAR_dev_username@$EC2_IP:/home/ubuntu/
+          ssh -o StrictHostKeyChecking=no -i key.pem \
+          $TF_VAR_dev_username@$EC2_IP <<'EOF'
+            chmod +x /home/ubuntu/install-monitoring.sh
+            bash /home/ubuntu/install-monitoring.sh
+          EOF
 
       - name: MariaDB Backup to S3
         run: |
-          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP <<EOF
+          ssh -o StrictHostKeyChecking=no -i key.pem \
+          $TF_VAR_dev_username@$EC2_IP <<EOF
             set -e
             TIMESTAMP=\$(date +%F-%H%M)
             mysqldump -h ${{ env.DB_ENDPOINT }} \
