Deploy Wordpress

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -10,6 +10,7 @@ jobs:
     runs-on: ubuntu-latest
 
     env:
+      TF_LOG: DEBUG
       AWS_REGION: eu-west-3
       TF_IN_AUTOMATION: true
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -160,26 +161,27 @@ jobs:
       - name: Set K3s Private IP from Terraform
         run: echo "K3S_IP=$(terraform output -raw k3s_public_ip)" >> $GITHUB_ENV
 
-        # - name: Create TLS Secret in K3s via SSH
-        # run: |
-        # echo "Creating Kubernetes TLS Secret in K3s cluster..."
-        #  ssh -o StrictHostKeyChecking=no -i key.pem \
-        #  "${{ secrets.DEV_USERNAME }}@${{ env.K3S_IP }}" bash << EOF
-        #    if command -v kubectl >/dev/null 2>&1; then
-        #      KUBECTL="kubectl"
-        #    elif command -v k3s >/dev/null 2>&1; then
-        #      KUBECTL="k3s kubectl"
-        #    else
-        #      echo "Neither kubectl nor k3s found. Aborting."
-        #      exit 1
-        #    fi
-        #    $KUBECTL get secret tls-secret --namespace default \
-        #    >/dev/null 2>&1 || \
-        #    $KUBECTL create secret tls tls-secret \
-        #    --cert=/etc/nginx/ssl/cert.pem \
-        #    --key=/etc/nginx/ssl/tls.key \
-        #    --namespace default
-        #  EOF
+      - name: Create TLS Secret in K3s via SSH
+        run: |
+          echo "Creating Kubernetes TLS Secret in K3s cluster..."
+          ssh -o StrictHostKeyChecking=no -i key.pem \
+          "${{ secrets.DEV_USERNAME }}@${{ env.K3S_IP }}" \
+           bash << EOF
+            set -e
+            if command -v kubectl >/dev/null 2>&1; then
+              KUBECTL="kubectl"
+            elif command -v k3s >/dev/null 2>&1; then
+              KUBECTL="k3s kubectl"
+            else
+              echo "Neither kubectl nor k3s found – aborting."
+              exit 1
+            fi
+
+            $KUBECTL delete secret wpf-tls --ignore-not-found
+            $KUBECTL create secret tls wpf-tls \
+            --cert=/etc/nginx/ssl/cert.pem \
+            --key=/etc/nginx/ssl/tls.key
+          EOF
 
       - name: Deploy WordPress & PrestaShop via K3s on EC2
         run: |
@@ -187,9 +189,11 @@ jobs:
           echo "DB_ENDPOINT=$(terraform output -raw db_endpoint)" \
           >> $GITHUB_ENV
           echo "DB_NAME=$(terraform output -raw db_name)" >> $GITHUB_ENV
-          scp -o StrictHostKeyChecking=no -i key.pem -r ./k8s/wordpress \
+          scp -o StrictHostKeyChecking=no -i key.pem -r \
+          ../../../k8s/wordpress \
           "${{ secrets.DEV_USERNAME }}@${{ env.K3S_IP }}":/home/ubuntu/
-          scp -o StrictHostKeyChecking=no -i key.pem -r ./k8s/prestashop \
+          scp -o StrictHostKeyChecking=no -i key.pem -r \
+          ../../../k8s/prestashop \
           "${{ secrets.DEV_USERNAME }}@${{ env.K3S_IP }}":/home/ubuntu/
           ssh -o StrictHostKeyChecking=no -i key.pem \
           "${{ secrets.DEV_USERNAME }}@${{ env.K3S_IP }}" bash << EOF
