Add cert to k3c

diff --git a/.github/workflows/terraform-apply-nocert.yml b/.github/workflows/terraform-apply-nocert.yml
--- a/.github/workflows/terraform-apply-nocert.yml
+++ b/.github/workflows/terraform-apply-nocert.yml
@@ -79,10 +79,10 @@ jobs:
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
           chmod 600 key.pem
 
-      - name: Extract TLS Outputs to Files
-        run: |
-          echo "$(terraform output -raw tls_cert)" > cert.pem
-          echo "$(terraform output -raw tls_key)" > tls.key
+          #  - name: Extract TLS Outputs to Files
+          # run: |
+          # echo "$(terraform output -raw tls_cert)" > cert.pem
+          # echo "$(terraform output -raw tls_key)" > tls.key
       - name: Installing nginx if needed
         run: |
           echo "Installing and configuring NGINX on EC2..."
@@ -101,53 +101,54 @@ jobs:
             fi
           EOF
 
-      - name: Upload TLS to EC2 & Configure NGINX
-        run: |
-          echo "Uploading certs and configuring NGINX on EC2..."
-          scp -o StrictHostKeyChecking=no \
-              -i key.pem \
-              cert.pem tls.key \
-               "${{ secrets.DEV_USERNAME }}@$EC2_IP":/tmp/
+          # - name: Upload TLS to EC2 & Configure NGINX
+          # run: |
+          # echo "Uploading certs and configuring NGINX on EC2..."
+          # scp -o StrictHostKeyChecking=no \
+          #    -i key.pem \
+          #    cert.pem tls.key \
+          #     "${{ secrets.DEV_USERNAME }}@$EC2_IP":/tmp/
 
-          ssh -o StrictHostKeyChecking=no -i key.pem \
-           "${{ secrets.DEV_USERNAME }}@$EC2_IP" << 'EOF'
-            sudo mkdir -p /etc/nginx/ssl
-            sudo mv -v  /tmp/cert.pem /etc/nginx/ssl/
-            sudo mv -v /tmp/tls.key /etc/nginx/ssl/
-            sudo chown root:root /etc/nginx/ssl/*
-            sudo chmod 644 /etc/nginx/ssl/*
-            ls -l /etc/nginx/ssl/cert.pem /etc/nginx/ssl/tls.key || exit 1
-            sudo tee /etc/nginx/sites-available/default > /dev/null << 'EOL'
-              server {
-                listen 443 ssl;
-                server_name wpf.drachenbyte.ddns-ip.net;
+          # ssh -o StrictHostKeyChecking=no -i key.pem \
+          # "${{ secrets.DEV_USERNAME }}@$EC2_IP" << 'EOF'
+          #  sudo mkdir -p /etc/nginx/ssl
+          #  sudo mv -v  /tmp/cert.pem /etc/nginx/ssl/
+          #  sudo mv -v /tmp/tls.key /etc/nginx/ssl/
+          #  sudo chown root:root /etc/nginx/ssl/*
+          #  sudo chmod 644 /etc/nginx/ssl/*
+          #  ls -l /etc/nginx/ssl/cert.pem /etc/nginx/ssl/tls.key || exit 1
+          #  sudo tee /etc/nginx/sites-available/default > /dev/null << 'EOL'
+          #    server {
+          #      listen 443 ssl;
+          #      server_name wpf.drachenbyte.ddns-ip.net;
+          #
+          #      ssl_certificate /etc/nginx/ssl/cert.pem;
+          #      ssl_certificate_key /etc/nginx/ssl/tls.key;
+          #
+          #      location / {
+          #        proxy_pass http://localhost:3000;
+          #        proxy_set_header Host \$host;
+          #        proxy_set_header X-Real-IP \$remote_addr;
+          #      }
+          #    }
 
-                ssl_certificate /etc/nginx/ssl/cert.pem;
-                ssl_certificate_key /etc/nginx/ssl/tls.key;
+          #   server {
+          #      listen 443 ssl;
+          #      server_name prestaf.drachenbyte.ddns-ip.net;
+          #
+          #      ssl_certificate /etc/nginx/ssl/cert.pem;
+          #      ssl_certificate_key /etc/nginx/ssl/tls.key;
+          #
+          #      location / {
+          #        proxy_pass http://localhost:4000;
+          #        proxy_set_header Host \$host;
+          #        proxy_set_header X-Real-IP \$remote_addr;
+          #      }
+          #    }
+          # EOL
 
-                location / {
-                  proxy_pass http://localhost:3000;
-                  proxy_set_header Host \$host;
-                  proxy_set_header X-Real-IP \$remote_addr;
-                }
-              }
-
-              server {
-                listen 443 ssl;
-                server_name prestaf.drachenbyte.ddns-ip.net;
-
-                ssl_certificate /etc/nginx/ssl/cert.pem;
-                ssl_certificate_key /etc/nginx/ssl/tls.key;
-
-                location / {
-                  proxy_pass http://localhost:4000;
-                  proxy_set_header Host \$host;
-                  proxy_set_header X-Real-IP \$remote_addr;
-                }
-              }
-            EOL
-            sudo systemctl restart nginx
-          EOF
+          # sudo systemctl restart nginx
+          # EOF
 
       - name: Terraform Output
         id: tfoutput
@@ -161,39 +162,27 @@ jobs:
       - name: Set K3s Private IP from Terraform
         run: echo "K3S_IP=$(terraform output -raw k3s_public_ip)" >> $GITHUB_ENV
 
-      - name: Copy TLS to K3s
-        run: |
-          scp -o StrictHostKeyChecking=no -i key.pem \
-          cert.pem tls.key \
-          "${{ secrets.DEV_USERNAME }}@${{ env.K3S_IP }}":/tmp/
-
-      - name: Create TLS Secret in K3s via SSH
-        run: |
-          echo "Creating Kubernetes TLS Secret in K3s cluster..."
-          ssh -o StrictHostKeyChecking=no -i key.pem \
-          "${{ secrets.DEV_USERNAME }}@${{ env.K3S_IP }}"  << 'EOF'
-            set -e
-            sudo mkdir -p /etc/nginx/ssl
-            sudo mv -v  /tmp/cert.pem /etc/nginx/ssl/
-            sudo mv -v /tmp/tls.key /etc/nginx/ssl/
-            sudo chown root:root /etc/nginx/ssl/*
-            sudo chmod 644 /etc/nginx/ssl/*
-            ls -l /etc/nginx/ssl/cert.pem /etc/nginx/ssl/tls.key || exit 1
-            if command -v kubectl >/dev/null 2>&1; then
-              kubectl delete secret wpf-tls --ignore-not-found || true
-              kubectl create secret tls wpf-tls \
-              --cert=/etc/nginx/ssl/cert.pem \
-              --key=/etc/nginx/ssl/tls.key
-            elif command -v k3s >/dev/null 2>&1; then
-              k3s delete secret wpf-tls --ignore-not-found || true
-              k3c create secret tls wpf-tls \
-              --cert=/etc/nginx/ssl/cert.pem \
-              --key=/etc/nginx/ssl/tls.key
-            else
-              echo "Neither kubectl nor k3s found – aborting."
-              exit 1
-            fi
-          EOF
+        #- name: Create TLS Secret in K3s via SSH
+        #run: |
+        #  echo "Creating Kubernetes TLS Secret in K3s cluster..."
+        #  ssh -o StrictHostKeyChecking=no -i key.pem \
+        #  "${{ secrets.DEV_USERNAME }}@${{ env.K3S_IP }}"  << 'EOF'
+        #    set -e
+        #    if command -v kubectl >/dev/null 2>&1; then
+        #      kubectl delete secret wpf-tls --ignore-not-found || true
+        #      kubectl create secret tls wpf-tls \
+        #    --cert=/etc/nginx/ssl/cert.pem \
+        #    --key=/etc/nginx/ssl/tls.key
+        #    elif command -v k3s >/dev/null 2>&1; then
+        #      k3s delete secret wpf-tls --ignore-not-found || true
+        #      k3c create secret tls wpf-tls \
+        #      --cert=/etc/nginx/ssl/cert.pem \
+        #      --key=/etc/nginx/ssl/tls.key
+        #    else
+        #      echo "Neither kubectl nor k3s found – aborting."
+        #      exit 1
+        #    fi
+        #  EOF
 
       - name: Deploy WordPress & PrestaShop via K3s on EC2
         run: |
